services:
  - type: web
    name: mudcreek
    runtime: docker
    disk:
      name: storage
      mountPath: /rails/storage
      sizeGB: 10
    preDeployCommand: "bundle exec rails db:prepare && bundle exec rails db:migrate:cache db:migrate:queue db:migrate:cable"
