default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mudcreek_development

test:
  <<: *default
  database: mudcreek_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database_tasks: false
